"""Add new column to Todo table

Revision ID: 20d4859959cb
Revises: e9b01af0f584
Create Date: 2024-11-22 11:59:35.320204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d4859959cb'
down_revision: Union[str, None] = 'e9b01af0f584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('user_id', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'user_id')
    # ### end Alembic commands ###
