"""Add age column to User table

Revision ID: a2e652b7f5d1
Revises: 0b439220f45d
Create Date: 2024-11-21 13:09:55.336541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e652b7f5d1'
down_revision: Union[str, None] = '0b439220f45d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.Boolean(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='todos_pkey')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###
